---
title: "Stats Over Time"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: spacelab
    css: www/garden.css
    includes:
      in_header: cssloaders_in_header.html
runtime: shiny
resource_files:
- "mlflow-291816-6d2188fa7f42.json"
- www/ComicSans.ttf
---

```{r setup, include=FALSE}
# Lens Stats over time for user
library(ghql)
library(tidyverse)
library(magick)
library(shiny)
library(flexdashboard)
library(plotly)
library(scales)
library(ggdark)
library(prophet)
library(cowplot)
library(bigrquery)
library(DBI)
library(DT)
# bigquery auth
bigrquery::bq_auth(path = "YOUR .JSON SERVICE ACCOUNT API KEY HERE")
# import lens logo to add to plots
lens_png = image_read("lens_logo.png")
# font
# dir.create('~/.fonts')
# file.copy("www/ComicSans.ttf", "~/.fonts")
# system('fc-cache -f ~/.fonts')

# remove scientific notation
options(scipen = 999)
# Remove messages and warnings
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
# Also hide code chunks
knitr::opts_chunk$set(echo = FALSE)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
textInput("handle", "Enter Lens Handle", value = "chriscomrie.lens", placeholder = "chriscomrie.lens")
# forecast days
sliderInput('forecast_days', 'Number of Days for Forecast', min=1, max=150, step=1, value=30)

# h5("Forecast made using Facebook Prophet")

# Add apply button
#actionButton("apply_filters", "Apply")
```


Column {.tabset}
-----------------------------------------------------------------------

### Chart

```{r}
data_reactive <- reactive({
  showNotification(paste0("Now pulling data for user: ", input$handle))
  
  # connect to bigquery
  bquery_con <- dbConnect(
    bigrquery::bigquery(),
    project = "lens-public-data",
    dataset = "polygon",
    billing = "mlflow-291816"
  )
  
  
  # query for profile info
  sql_query = paste0("select 
    profile_id,
    owned_by,
    name,
    handle,
    profile_picture_s3_url,
    block_timestamp
  from public_profile
  where handle = '",input$handle,"'")
  # get user data
  user_data = dbGetQuery(bquery_con, sql_query)
  # get address
  profile_id = user_data$profile_id
  
  # query
  sql_query = paste0("WITH daily_followers AS (
    SELECT
      follow_profile_id,
      DATE(block_timestamp) AS day,
      COUNT(address) AS daily_followers_count
    FROM `lens-public-data.polygon.public_follower`
    WHERE follow_profile_id = '",profile_id,"'
    GROUP BY follow_profile_id, DATE(block_timestamp)
  ),
  running_total AS (
    SELECT
      df.follow_profile_id,
      df.day,
      SUM(df.daily_followers_count) OVER (PARTITION BY df.follow_profile_id ORDER BY df.day) AS followers
    FROM daily_followers df
  )
  SELECT
    rt.follow_profile_id as profile_id,
    rt.day,
    rt.followers
  FROM running_total rt
  ORDER BY rt.day DESC")
  
  # Download data
  data = dbGetQuery(bquery_con, sql_query)
  
  # disconnect
  dbDisconnect(bquery_con)
  
  # convert to numeric
  data$followers = as.numeric(data$followers)
  # return the data
  data
})

# Use observeEvent for updating the text input
observeEvent(input$handle, {
  data <- data_reactive()
})

# Modify the renderPlot function
output$plot = renderPlot({
  # Get data from the reactive expression
  data <- data_reactive()
  
  # Make predictions with fb prophet
  # only keep two cols
  preds = select(data, day, "followers")
  # rename columms
  preds = rename(preds, y = "followers", ds = 'day')
  # look at daily change
  # preds = mutate(preds, y = y-lead(y))
  # run predictions
  m = prophet(preds)
  future <- make_future_dataframe(m, periods = input$forecast_days)
  # make forecast
  forecast <- predict(m, future)
  # plot predictions
  totals_viz = plot(m, forecast) +
    geom_point(color='#AAFE2D') +
      labs(color = 'App') +
    # geom_line(aes(y = totalPublications, colour = "Total Publications")) + 
    dark_theme_minimal() +
    ggtitle(paste0('Follower by Day - ', input$handle)) +
    ylab(str_to_title(gsub("([a-z])([A-Z])", "\\1 \\2", "followers"))) +
    xlab('Date') +
    scale_y_continuous(labels=comma) +
    theme(
      #plot.title = element_text(size = 14, family = "Comic Sans MS"),
      axis.title.x = element_blank()
    )
    # scale_colour_manual(values = c("#00501f", "#abfe2d"))
  # add logo
  totals_viz = ggdraw() +
    draw_plot(totals_viz) +
    draw_image(lens_png, x = 0.4, y = 0.42, scale = 0.09)
  totals_viz
})

shinycssloaders::withSpinner(plotOutput('plot'))
```


### Table

```{r}
# Render the DT table
output$data_table <- renderDT({
  # Get data from the reactive expression
  data <- data_reactive()
  
  # Render the data table
  datatable(data,
            escape=FALSE,
            extensions = "Buttons", rownames = FALSE,
            options = list(paging = FALSE,
                           scrollX=TRUE, 
                           scrollY = "470px",
                           searching = TRUE,
                           ordering = TRUE,
                           dom = 'Bfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf'),
                           pageLength=200000, 
                           lengthMenu=c(5,7,10) ))
})

shinycssloaders::withSpinner(dataTableOutput('data_table'))
```

